# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: hexo generate

on:
  push:
    branches: master
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: step node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: check
      run: |
       node -v
       npm -v
    - name: Install dependencies
      run: |
        npm i -g hexo-cli
        npm ci
    - name: hexo generator public file
      run: |
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        GIT_NAME: sjywz
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: https://github.com/sjywz/sjywz.github.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" gh-pages:gh-pages
        
    
    

